name: CI

on:
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
